annual_reports:
  - url: "https://www.sjotungan.se/public_html/new2016/images/information/arsmotes_handlingar/2025/stamma2025.pdf"
    finance_period: 2024
    local_path: "data/annual_reports/stamma2025.pdf"
  - url: "https://www.sjotungan.se/public_html/new2016/images/information/arsmotes_handlingar/2024/stamma-2024.pdf"
    finance_period: 2023
    local_path: "data/annual_reports/stamma-2024.pdf"
  - url: "https://www.sjotungan.se/public_html/new2016/images/information/arsmotes_handlingar/2023/stamma-2023.pdf"
    finance_period: 2022
    local_path: "data/annual_reports/stamma-2023.pdf"
  - url: "https://www.sjotungan.se/public_html/new2016/images/information/arsmotes_handlingar/2022/stamma_kallelse_2022.pdf"
    finance_period: 2021
    local_path: "data/annual_reports/stamma_kallelse_2022.pdf"
  - url: "https://www.sjotungan.se/public_html/new2016/images/information/arsmotes_handlingar/2021/stamma_kallelse-2021.pdf"
    finance_period: 2020
    local_path: "data/annual_reports/stamma_kallelse-2021.pdf"
  - url: "https://www.sjotungan.se/public_html/new2016/images/information/arsmotes_handlingar/2020/BRF_Sjotungan_arsredovisning_2019.pdf"
    finance_period: 2019
    local_path: "data/annual_reports/BRF_Sjotungan_arsredovisning_2019.pdf"
  - url: "https://www.sjotungan.se/public_html/new2016/images/information/arsmotes_handlingar/2019/kallelse%20stamma%202019.pdf"
    finance_period: 2018
    local_path: "data/annual_reports/kallelse_stamma_2019.pdf"
  - url: "https://www.sjotungan.se/public_html/new2016/images/information/arsmotes_handlingar/2018/kallelse%20stamma2018.pdf"
    finance_period: 2017
    local_path: "data/annual_reports/kallelse_stamma2018.pdf"
